CREATE DATABASE IF NOT EXISTS task;
USE task;

CREATE TABLE IF NOT EXISTS products (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    supplierEmail VARCHAR(255) NOT NULL,
    count INT NOT NULL,
    price DECIMAL(10, 2) NOT NULL
);